"""
ingestion/chunker.py — Hierarchy-preserving text chunking for Markdown.

Uses LangChain's MarkdownHeaderTextSplitter to split the continuous
markdown document generated by Marker into coherent chunks, while retaining
header hierarchy (Chapter -> Section -> Subsection).
"""

from __future__ import annotations

import re
from loguru import logger
from langchain.text_splitter import MarkdownHeaderTextSplitter, RecursiveCharacterTextSplitter
from app.core.config import get_settings

settings = get_settings()

class MarkdownChunker:
    """
    Splits continuous Markdown text into overlapping chunks while preserving
    hierarchical metadata based on markdown headers (#, ##, ###).
    """

    def __init__(
        self,
        chunk_size: int = settings.chunk_size,
        chunk_overlap: int = settings.chunk_overlap,
    ):
        self.headers_to_split_on = [
            ("#", "Header 1"),
            ("##", "Header 2"),
            ("###", "Header 3"),
            ("####", "Header 4"),
        ]
        self.md_splitter = MarkdownHeaderTextSplitter(headers_to_split_on=self.headers_to_split_on)
        self.text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=chunk_size, 
            chunk_overlap=chunk_overlap,
            separators=["\n\n", "\n", ". ", " ", ""]
        )

    def chunk_markdown(
        self, 
        markdown_text: str, 
        manual_id: str, 
        manual_name: str, 
        filename: str,
        image_filenames: list[str] = None
    ) -> list[dict]:
        """
        Split markdown text into chunks with full hierarchical metadata.

        Args:
            markdown_text: The full markdown string from Marker.
            manual_id: Unique identifier for the manual.
            manual_name: Display name.
            filename: Original PDF filename.
            image_filenames: List of image filenames extracted by marker to check for presence in chunks.

        Returns:
            List of chunk dicts.
        """
        if image_filenames is None:
            image_filenames = []
            
        md_docs = self.md_splitter.split_text(markdown_text)
        splits = self.text_splitter.split_documents(md_docs)

        chunks: list[dict] = []
        
        for i, split in enumerate(splits):
            text = split.page_content.strip()
            if not text:
                continue
                
            metadata = split.metadata
            
            # Resolve hierarchy
            h1 = metadata.get("Header 1", "Unknown Chapter")
            h2 = metadata.get("Header 2", "General")
            h3 = metadata.get("Header 3", "")
            
            # Construct hierarchy path
            hierarchy_parts = [manual_name, h1, h2]
            if h3:
                hierarchy_parts.append(h3)
            # Remove "General" if we have deeper sections to avoid "Chap > General > Sub" unless needed
            if h2 == "General" and h3:
                hierarchy_parts.remove("General")
                
            hierarchy_path = " > ".join(hierarchy_parts)
            
            # Detect content type
            content_type = "text"
            if "|" in text and "-|-" in text:
                content_type = "table"
            elif re.search(r"(?i)(?:error|fault|alarm)\s*(?:code|#|number)", text):
                content_type = "error_code"
            elif re.search(r"(?i)(?:warning|caution|danger)", text):
                content_type = "safety"
            elif re.search(r"(?m)^[\s]*[-*]\s", text):
                content_type = "list"

            # Check if this chunk references any of the extracted images
            # Marker usually writes ![image_name](image_path) or just the filename in the text
            images_in_chunk = []
            for img_name in image_filenames:
                if img_name in text:
                    images_in_chunk.append(img_name)

            chunks.append({
                "chunk_id": f"{manual_id}_{i}",
                "manual_id": manual_id,
                "manual_name": manual_name,
                "filename": filename,
                "chapter": h1,
                "section": h2 if not h3 else f"{h2} > {h3}",
                "page": 0,  # Page numbers are lost in pure Markdown conversion
                "chunk_index": i,
                "text": text,
                "content_type": content_type,
                "has_tables": content_type == "table",
                "has_images": len(images_in_chunk) > 0,
                "images_referenced": images_in_chunk,
                "hierarchy_path": hierarchy_path,
            })

        logger.info(f"Generated {len(chunks)} Markdown chunks for '{filename}'")
        return chunks


def chunk_pages(
    markdown_text: str,
    manual_id: str,
    filename: str,
    manual_name: str,
    image_filenames: list[str] = None,
    chunk_size: int = settings.chunk_size,
    chunk_overlap: int = settings.chunk_overlap,
) -> list[dict]:
    """Convenience function wrapper for backward compatibility with pdf_service."""
    chunker = MarkdownChunker(chunk_size=chunk_size, chunk_overlap=chunk_overlap)
    return chunker.chunk_markdown(markdown_text, manual_id, manual_name, filename, image_filenames)
